(function(x,z){function oa(e){return e<<1}function pa(e){return e<<1}function S(){return z.pointerLockElement===w||z.mozPointerLockElement===w||z.webkitPointerLockElement===w}function qa(e){T(e)}function U(e,b){F=e;G=b;l=p=e;m=s=b;A=p<<1;B=s<<1}function ra(e){if(y)return H=!1,T(e),!1;S()?V||(V=!0,U(l,m)):(V=!1,y||I.checked||w.requestPointerLock&&w.requestPointerLock());if(H)H=!1,J();else if(T(e),(e.ctrlKey||e.shiftKey)&&!C.checked)W=!0,N=l,O=m;else if(100<t-aa&&p==l&&s==m){aa=t;D.push([p<<1,s<<1,
t]);sa(p,s);var b=[p,s];K.push(b);setTimeout(function(){K.remove(b)},1E3)}return!1}function ta(e){W=!1}function ua(){function e(b,e){q=new WebSocket("wss://cursors-io.hellogame.repl.co");q.binaryType="arraybuffer";q.onopen=va;q.onmessage=wa;q.onclose=xa;q.onerror=ya}null==q&&(za?e("127.0.0.1",null):e())}function Aa(){x.localStorage&&I&&(x.localStorage.setItem("noCursorLock",I.checked?"1":"0"),x.localStorage.setItem("noDrawings",C.checked?"1":"0"))}function T(e){if(S()){var b=e.webkitMovementX||e.mozMovementX||
e.movementX||0;e=e.webkitMovementY||e.mozMovementY||e.movementY||0;300>Math.abs(b)+Math.abs(e)&&X(A+b,B+e)}else e.offsetX?X(e.offsetX,e.offsetY):e.layerX&&X(e.layerX,e.layerY);if(y)l=p,m=s;else if(Y(),!S()||p==l&&s==m||(e=b=0,p>l&&(b=1),s>m&&(e=1),p=l,s=m,A=(p<<1)+b,B=(s<<1)+e),W&&(N!=l||O!=m)&&50<t-ba){b=N;e=O;var a=l,d=m;if(!y&&null!=q&&q.readyState==WebSocket.OPEN){var g=new ArrayBuffer(9),f=new DataView(g);f.setUint8(0,3);f.setUint16(1,b,!0);f.setUint16(3,e,!0);f.setUint16(5,a,!0);f.setUint16(7,
d,!0);q.send(g)}N=l;O=m;ba=t}}function X(e,b){A=e;B=b;p=A>>1;s=B>>1}function Y(){var e=l,b=m;if(P(l,m)){var a;a:{a=l;var d=m,g=[],f=new Uint8Array(12E4);g.push([a,d]);f[a+400*d]=1;do{var k=g.shift(),h=k[0],k=k[1];if(!(0>h||0>k||400<=h||300<=k)){if(!P(h,k)){a={x:h,y:k};break a}f[h-1+400*k]||(g.push([h-1,k]),f[h-1+400*k]=1);f[h+1+400*k]||(g.push([h+1,k]),f[h+1+400*k]=1);f[h+400*(k-1)]||(g.push([h,k-1]),f[h+400*(k-1)]=1);f[h+400*(k+1)]||(g.push([h,k+1]),f[h+400*(k+1)]=1)}}while(0<g.length);a={x:a,y:d}}l=
a.x;m=a.y}if(l!=p||m!=s)a=ca(l,m,p,s),l=a.x,m=a.y;da(F,G,e,b)&&!da(F,G,l,m)&&(J(e,b),J(l,m));a:{for(e=0;e<n.length;e++)if(b=n[e],2==b.type&&!(l<b.x||m<b.y||l>=b.x+b.width||m>=b.y+b.height)){e=!0;break a}e=!1}e&&J()}function Z(){Q.set(Ba);n=[];D=[];L=[]}function va(){Z();console.log("Connected!")}function xa(a){Z();console.log("Socket closed: "+a.reason)}function ya(a){console.log("Socket error")}function Ca(a,b){for(var c="",d=0,g=0;0!=(g=a.getUint8(b));++b)d<<=8,d|=g,g&128||(c+=String.fromCharCode(d),
d=0);0!=d&&(c+=String.fromCharCode(d));return[c,b+1]}function Da(a,b){setTimeout(function(){var c=a.getUint16(b,!0),d=0;a:for(;d<c;d++){for(var g=a.getUint16(b+2+4*d,!0),f=a.getUint16(b+4+4*d,!0),k=0;k<K.length;k++){var h=K[k];if(h[0]==g&&h[1]==f){K.splice(k,1);continue a}}D.push([g<<1,f<<1,t])}},100);return b+2+4*a.getUint16(b,!0)}function Ea(a,b){!C.checked&&setTimeout(function(){for(var c=a.getUint16(b,!0),d=0;d<c;d++){var g=a.getUint16(b+2+8*d,!0),f=a.getUint16(b+4+8*d,!0),k=a.getUint16(b+6+8*
d,!0),h=a.getUint16(b+8+8*d,!0);L.push([g<<1,f<<1,k<<1,h<<1,t])}},50);return b+2+8*a.getUint16(b,!0)}function wa(a){a=a.data;var b=new DataView(a);switch(b.getUint8(0)){case 0:ea=b.getUint32(1,!0);break;case 1:var c;fa=c=b.getUint16(1,!0);ga=100<=c;var d=[],g;for(g in v)v.hasOwnProperty(g)&&d.push(g);for(var f=0;f<c;f++){g=b.getUint32(3+8*f,!0);var k=b.getUint16(7+8*f,!0),h=b.getUint16(9+8*f,!0);if(g!=ea)if(null!=v[g]){for(var r=0;r<d.length;r++)if(d[r]==g){d.splice(r,1);break}g=v[g];g.oldX=g.getX();
g.oldY=g.getY();g.newX=k;g.newY=h;g.time=t}else v[g]=new ha(k,h)}for(f=0;f<d.length;f++)delete v[d[f]];c=Da(b,3+8*c);g=b.getUint16(c,!0);c+=2;for(d=0;d<g;d++){a:for(k=b.getUint32(c,!0),f=0;f<n.length;f++)if(n[f].id==k){var l=n[f];if(1==l.type)for(var k=l.x|0,h=l.y|0,r=l.width|0,l=l.height|0,m=h;m<h+l;++m)for(var p=k;p<k+r;++p)--Q[p+400*m];n.splice(f,1);break a}c+=4}g=b.getUint16(c,!0);c+=2;for(d=0;d<g;d++){a:{f=b.getUint32(c,!0);for(k=0;k<n.length;k++)if(n[k].id==f){f=n[k];break a}f={id:f};n.push(f)}c+=
4;c=ia(b,c,f)}c=Ea(b,c);if(a.byteLength<c+4)break;$=b.getUint32(c,!0);break;case 4:Z();U(b.getUint16(1,!0),b.getUint16(3,!0));g=b.getUint16(5,!0);c=7;for(d=0;d<g;d++)f={},f.id=b.getUint32(c,!0),c+=4,c=ia(b,c,f),n.push(f);a.byteLength>=c+4?u=Math.max(u,b.getUint32(c,!0)):a.byteLength>=c+2&&(u=Math.max(u,b.getUint16(c,!0)));Y();break;case 5:U(b.getUint16(1,!0),b.getUint16(3,!0)),9<=b.byteLength?u=Math.max(u,b.getUint32(5,!0)):7<=b.byteLength&&(u=Math.max(u,b.getUint16(5,!0))),Y()}}function J(a,b){if(!y&&
!H&&null!=q&&q.readyState==WebSocket.OPEN&&("undefined"==typeof a&&(a=l),"undefined"==typeof b&&(b=m),a!=F||b!=G)){var c=new ArrayBuffer(9),d=new DataView(c);d.setUint8(0,1);d.setUint16(1,a,!0);d.setUint16(3,b,!0);d.setUint32(5,u,!0);q.send(c);F=a;G=b}}function sa(a,b){if(!y&&null!=q&&q.readyState==WebSocket.OPEN){var c=new ArrayBuffer(9),d=new DataView(c);d.setUint8(0,2);d.setUint16(1,a,!0);d.setUint16(3,b,!0);d.setUint32(5,u,!0);q.send(c)}}function ia(a,b,c){function d(){c.x=a.getUint16(b,!0);b+=
2;c.y=a.getUint16(b,!0);b+=2;c.width=a.getUint16(b,!0);b+=2;c.height=a.getUint16(b,!0);b+=2}function g(){for(var d=a.getUint32(b,!0).toString(16);6>d.length;)d="0"+d;b+=4;c.color="#"+d}var f=a.getUint8(b);b+=1;c.type=f;switch(f){case 255:break;case 0:c.x=a.getUint16(b,!0);b+=2;c.y=a.getUint16(b,!0);b+=2;c.size=a.getUint8(b);b+=1;c.isCentered=!!a.getUint8(b);b+=1;f=Ca(a,b);c.text=f[0];b=f[1];break;case 1:d();var k=!c.color;g();var f=c.x|0,h=c.y|0,l=c.width|0,m=c.height|0;if(k)for(k=h;k<h+m;++k)for(var n=
f;n<f+l;++n)++Q[n+400*k];break;case 2:d();c.isBad=!!a.getUint8(b);b+=1;break;case 3:d();c.count=a.getUint16(b,!0);b+=2;g();break;case 4:d();c.count?c.count>a.getUint16(b,!0)&&(c.lastClickAt=t):c.lastClickAt=0;c.count=a.getUint16(b,!0);b+=2;g();break;default:throw Error("Unknown object type "+f);}return b}function ja(){a.clearRect(0,0,800,600);a.save();if(null!=q&&q.readyState!=WebSocket.OPEN||H){var e;if(null==q)e="Click to begin";else switch(q.readyState){case WebSocket.CONNECTING:e="Connecting";
break;case WebSocket.CLOSING:case WebSocket.CLOSED:e="Lost connection to server";break;default:e="Click to begin"}a.font="60px NovaSquare";a.fillText(e,400-a.measureText(e).width/2,315);ka();la(!1)}else{a.fillStyle="#000000";a.save();a.globalAlpha=1;Fa();for(e=0;e<n.length;e++){var b=n[e];if(0==b.type){a.font=b.size+"px NovaSquare";var c=b.x<<1,d=b.y<<1;b.isCentered&&(c-=a.measureText(b.text).width/2);a.fillStyle="#000000";a.fillText(b.text,c,d)}else if(1==b.type)a.fillStyle=b.color,a.fillRect(b.x<<
1,b.y<<1,b.width<<1,b.height<<1),a.strokeStyle="#000000",a.globalAlpha=.2,a.lineWidth=2,a.strokeRect((b.x<<1)+1,(b.y<<1)+1,(b.width<<1)-2,(b.height<<1)-2),a.globalAlpha=1;else if(2==b.type)a.fillStyle=b.isBad?"#FF0000":"#00FF00",a.globalAlpha=.2,a.fillRect(b.x<<1,b.y<<1,b.width<<1,b.height<<1),a.globalAlpha=1;else if(3==b.type){var c=b.x<<1,d=b.y<<1,g=b.width<<1,f=b.height<<1;a.fillStyle=b.color;a.globalAlpha=.2;a.fillRect(c,d,g,f);a.globalAlpha=.5;a.fillStyle="#000000";40>b.width||40>b.height?(a.font=
"30px NovaSquare",a.fillText(b.count,c+g/2-a.measureText(b.count).width/2,d+f/2+10)):(a.font="60px NovaSquare",a.fillText(b.count,c+g/2-a.measureText(b.count).width/2,d+f/2+20));a.globalAlpha=1}else if(4==b.type){c=b.x<<1;d=b.y<<1;g=b.width<<1;f=b.height<<1;a.fillStyle=b.color;a.strokeStyle=b.color;a.globalAlpha=1;a.fillRect(c,d,g,f);a.globalAlpha=.2;a.fillStyle="#000000";a.fillRect(c,d,g,f);a.globalAlpha=1;a.fillStyle=b.color;var k=150>t-b.lastClickAt,h=k?8:12;a.fillRect(c+h,d+h,g-2*h,f-2*h);a.strokeStyle=
"#000000";a.globalAlpha=.1;a.beginPath();a.moveTo(c,d);a.lineTo(c+h,d+h);a.moveTo(c+g,d);a.lineTo(c+g-h,d+h);a.moveTo(c,d+f);a.lineTo(c+h,d+f-h);a.moveTo(c+g,d+f);a.lineTo(c+g-h,d+f-h);a.moveTo(c,d);a.rect(c,d,g,f);a.rect(c+h,d+h,g-2*h,f-2*h);a.stroke();a.fillStyle="#000000";a.globalAlpha=.5;50>b.width||50>b.height?(a.font="35px NovaSquare",a.fillText(b.count,c+g/2-a.measureText(b.count).width/2,d+f/2+13)):(a.font="45px NovaSquare",a.fillText(b.count,c+g/2-a.measureText(b.count).width/2,d+f/2+16));
k&&(a.fillStyle="#000000",a.globalAlpha=.15,a.fillRect(c+h,d+h,g-2*h,f-2*h));a.globalAlpha=1}}a.restore();y||(a.font="12px NovaSquare",a.strokeStyle="#000000",a.fillStyle="#FFFFFF",a.lineWidth=2.5,e=ga?"Area too full, not all cursors are shown":30<fa?"Area too full, drawing is disabled":"Use shift+click to draw",a.globalAlpha=.5,a.strokeText(e,10,590),a.globalAlpha=1,a.fillText(e,10,590),0!=$&&(e=$+" players online",b=a.measureText(e).width,a.globalAlpha=.5,a.strokeText(e,790-b,590),a.globalAlpha=
1,a.fillText(e,790-b,590)));ka();if(!C.checked){a.save();a.strokeStyle="#000000";a.lineWidth=1;t=+new Date;for(e=0;e<L.length;e++)b=L[e],c=10-(t-b[4])/1E3,0>=c?(L.splice(e,1),--e):(1<c&&(c=1),a.globalAlpha=.3*c,a.beginPath(),a.moveTo(b[0]-.5,b[1]-.5),a.lineTo(b[2]-.5,b[3]-.5),a.stroke());a.restore()}a.save();for(var l in v)v.hasOwnProperty(l)&&a.drawImage(M,oa(v[l].getX())-6,pa(v[l].getY())-6,23,30);a.restore();la(!0)}a.restore();x.requestAnimationFrame(ja)}function ka(){a.save();a.strokeStyle="#000000";
t=+new Date;for(var e=0;e<D.length;e++){var b=D[e],c=(t-b[2])/1E3,d=1-2*c;0>=d?(D.splice(e,1),--e):(c*=50,a.beginPath(),a.globalAlpha=.3*d,a.arc(b[0],b[1],c,0,2*Math.PI,!1),a.stroke())}a.restore()}function la(e){if(y)a.save(),a.globalAlpha=1,a.drawImage(M,A-5,B-5);else{var b=0,c=0;p!=l||s!=m?(a.save(),e&&(a.globalAlpha=.2,a.fillStyle="#FF0000",a.beginPath(),a.arc(A+2,B+8,20,0,2*Math.PI,!1),a.fill()),a.globalAlpha=.5,a.drawImage(M,A-5,B-5,23,30),a.restore()):(b=A&1,c=B&1);a.save();e&&(a.globalAlpha=
.2,a.fillStyle="#FFFF00",a.beginPath(),a.arc((l<<1)+b+2,(m<<1)+c+8,20,0,2*Math.PI,!1),a.fill());a.globalAlpha=1;a.drawImage(Ga,(l<<1)+b-5,(m<<1)+c-5,23,30)}a.restore()}function ha(a,b){this.oldX=this.newX=a;this.oldY=this.newY=b;this.time=t}function ma(a){return a*a*(3-2*a)}function ca(a,b,c,d){a|=0;b|=0;c|=0;d|=0;if(P(a,b))return{x:a,y:b};if(a==c&&b==d)return{x:c,y:d};var g=a,f=b;c=c-a|0;d=d-b|0;var k=0,h=0,l=0,m=0;0>c?k=-1:0<c&&(k=1);0>d?h=-1:0<d&&(h=1);0>c?l=-1:0<c&&(l=1);var n=Math.abs(c)|0,p=
Math.abs(d)|0;n<=p&&(n=Math.abs(d)|0,p=Math.abs(c)|0,0>d?m=-1:0<d&&(m=1),l=0);c=n>>1;for(d=0;d<=n&&!P(a,b);d++)g=a,f=b,c+=p,c>=n?(c-=n,a+=k,b+=h):(a+=l,b+=m);return{x:g,y:f}}function da(a,b,c,d){a=ca(a,b,c,d);return a.x==c&&a.y==d}function P(a,b){return 0>a||400<=a||0>b||300<=b?!0:Q[a+400*b]}var za="file:"==x.location.protocol,E,a,w,fa=0,p=0,s=0,A=0,B=0,l=0,m=0,F=-1,G=-1,I=null,C=null,M=new Image;M.src="img/cursor.png";var Ga=M,y=-1!=x.location.search.indexOf("editor"),D=[],L=[],t=0,aa=0,q=null,ea=
-1,v={},$=0,ga=!1,W=!1,N=0,O=0,ba=0,V=!1,H=!y&&!0,Q=new Uint8Array(12E4),n=[],K=[],R=x.devicePixelRatio;Array.prototype.remove=function(a){a=this.indexOf(a);return-1!=a?(this.splice(a,1),!0):!1};var u=0;ha.prototype={oldX:0,oldY:0,newX:0,newY:0,time:0,getX:function(){var a=this.newX-this.oldX,b=(t-this.time)/100,b=ma(0>=b?0:1<=b?1:b);return this.oldX+b*a},getY:function(){var a=this.newY-this.oldY,b=(t-this.time)/100,b=ma(0>=b?0:1<=b?1:b);return this.oldY+b*a}};var na=function(){function e(){var a=
0,b=0,c=p/10,d=s/10;k<c?(c=Math.ceil(c),a=Math.floor(k)):(c=Math.floor(c),a=Math.ceil(k));h<d?(d=Math.ceil(d),b=Math.floor(h)):(d=Math.floor(d),b=Math.ceil(h));if(a>c)var e=c,c=a,a=e;b>d&&(e=d,d=b,b=e);return{sx:a,sy:b,fx:c,fy:d}}function b(){f=!0;k=p/10;h=s/10}function c(a){return"0x"+parseInt(a.slice(1),16).toString(16).toUpperCase()}function d(a,b,c,d,e){a={x:10*~~(l/10)-~~(a/2)+c,y:10*~~(m/10)-~~(b/2)+d,width:a,height:b};for(var f in e)e.hasOwnProperty(f)&&(a[f]=e[f]);return a}function g(a,b){for(var c=
null,d=Number.POSITIVE_INFINITY,e=0;e<n.length;e++){var f=n[e];if(f.hasOwnProperty("x")&&f.hasOwnProperty("y")&&f.hasOwnProperty("width")&&f.hasOwnProperty("height")){var g=f.x+f.width/2,h=f.y+f.height/2,g=(a-g)*(a-g)+(b-h)*(b-h);g<d&&(d=g,c=f)}}return c}var f=!1,k=0,h=0,r=1,q=200,t=150,v=new Uint8Array(1200),u="#000000 #FF9999 #9999FF #FFFF99 #99FFFF #FF99FF #3333FF".split(" ");z.addEventListener("mouseup",function(){if(f){for(var a=e(),b=r,c=a.sy;c<a.fy;++c)for(var d=a.sx;d<a.fx;++d)v[d+40*c]=b;
f=!1}});z.addEventListener("mousemove",function(){});x.generateCode=function(){for(var a="class Level? : public Level {\npublic:\n\tLevel?() : Level("+q+", "+t+"){}\n\n\tvoid OnInit(){\n",a=a+("\t\tstd::vector<LevelObject*> wallByColor["+u.length+"];\n"),b=new Uint8Array(1200),d=[],e=0;30>e;++e)for(var f=0;40>f;++f)if(!b[f+40*e]){var g=v[f+40*e];if(0!=g){for(var h=f;40>f&&v[f+40*e]==g&&!b[f+40*e];)b[f+40*e]=!0,++f;var k=f--,l=k-h,m=e++;a:for(;30>e;){for(var p=h;p<k;++p){if(v[p+40*e]!=g)break a;if(b[p+
40*e])break a}for(p=h;p<k;++p)b[p+40*e]=!0;++e}k=e-m;e=m;d.push({x:10*h,y:10*m,width:10*l,height:10*k,color:g-1})}}for(b=0;b<d.length;b++)e=d[b],0==e.color?a+="\t\tAddObject(new ObjWall("+e.x+", "+e.y+", "+e.width+", "+e.height+", 0x000000));\n":(f=c(u[e.color]),a+="\t\twallByColor["+e.color+"].push_back(AddObject(new ObjWall("+e.x+", "+e.y+", "+e.width+", "+e.height+", "+f+")));\n");for(b=0;b<n.length;b++)d=n[b],0!=d.type&&(2==d.type?a+="\t\tAddObject(new ObjTeleport(LevelManager::GetNextLevel(this), "+
d.x+", "+d.y+", "+d.width+", "+d.height+"));\n":3==d.type?(a+="\t\tAddObject(new ObjAreaCounter(wallByColor["+d.colorCode+"], "+d.x+", "+d.y+", "+d.width+", "+d.height+", ",a+=d.count+", "+c(d.color)+"));\n"):4==d.type&&(a+="\t\tAddObject(new ObjClickBox(wallByColor["+d.colorCode+"], "+d.x+", "+d.y+", "+d.width+", "+d.height+", ",a+=d.count+", 1000, "+c(d.color)+"));\n"));return a+="\t}\n};\n"};z.addEventListener("keydown",function(a){if(y){var b=a.keyCode;65==b?(--r,0>r&&(r=u.length)):83==b?(++r,
r>u.length&&(r=0)):66==b?1>=r||n.push(d(40,40,5,5,{type:4,color:u[r-1],colorCode:r-1,count:5})):90==b?n.pop():87==b?n.push(d(50,50,-5,-5,{type:2,isBad:!1})):79==b?(q=l,t=m):78==b?1>=r||n.push(d(40,40,0,0,{type:3,color:u[r-1],colorCode:r-1,count:1})):37==b?(b=g(p,s),null!=b&&(a.shiftKey?b.width-=10:(b.x-=10,b.width+=10),0==b.width&&n.splice(n.indexOf(b),1))):39==b?(b=g(p,s),null!=b&&(a.shiftKey?(b.x+=10,b.width-=10):b.width+=10,0==b.width&&n.splice(n.indexOf(b),1))):38==b?(b=g(p,s),null!=b&&(a.shiftKey?
b.height-=10:(b.y-=10,b.height+=10),0==b.height&&n.splice(n.indexOf(b),1))):40==b&&(b=g(p,s),null!=b&&(a.shiftKey?(b.y+=10,b.height-=10):b.height+=10,0==b.height&&n.splice(n.indexOf(b),1)))}});return{renderEditor:function(){if(y){a.save();a.fillStyle="#FF0000";a.strokeStyle="#FF0000";a.lineWidth=1;a.globalAlpha=.09;a.beginPath();for(var b=0;400>b;b+=10)a.moveTo((b<<1)+.5,0),a.lineTo((b<<1)+.5,600);for(var c=0;300>c;c+=10)a.moveTo(0,(c<<1)+.5),a.lineTo(800,(c<<1)+.5);a.stroke();a.lineWidth=2;a.beginPath();
a.moveTo(400.5,0);a.lineTo(400.5,600);a.moveTo(0,300.5,0);a.lineTo(800,300.5);a.stroke();a.lineWidth=1;a.globalAlpha=1;a.fillStyle="#000000";for(var d=e(),c=0;300>c;c+=10)for(b=0;400>b;b+=10){var g=b/10|0,h=c/10|0,k=v[g+40*h];f&&g>=d.sx&&g<d.fx&&h>=d.sy&&h<d.fy&&(k=r);0!=k&&(a.fillStyle=u[k-1],a.fillRect(b<<1,c<<1,20,20))}a.save();a.globalAlpha=.09;a.fillStyle="#0000FF";a.beginPath();a.arc(q<<1,t<<1,20,0,2*Math.PI,!1);a.fill();a.restore();a.save();a.fillStyle="#FFFFFF";a.strokeStyle="#000000";a.lineWidth=
2.5;a.font="14px NovaSquare";a.globalAlpha=.5;a.strokeText("Current color: ",10,590);a.globalAlpha=1;a.fillText("Current color: ",10,590);0==r?a.fillText("ESR",105,590):(a.fillStyle="#000000",a.fillRect(104,575,22,22),a.fillStyle=u[r-1],a.fillRect(105,576,20,20));a.restore();a.restore()}},initEditor:function(){w.addEventListener("mousedown",b)}}}(),Fa=na.renderEditor,Ha=na.initEditor,Ba=new Uint8Array(12E4);Array.prototype.remove=function(a){a=this.indexOf(a);return-1!=a?(this.splice(a,1),!0):!1};
x.onload=function(){E=z.getElementById("canvas");a=E.getContext("2d");w=z.getElementById("canvasContainer")||E;E.width=800*R;E.height=600*R;a.scale(R,R);w.onmousemove=qa;w.onmousedown=ra;w.onmouseup=ta;I=z.getElementById("noCursorLock");C=z.getElementById("noDrawings");null!=localStorage&&(I.checked="1"==x.localStorage.getItem("noCursorLock")?!0:!1,C.checked="1"==x.localStorage.getItem("noDrawings")?!0:!1);x.onbeforeunload=Aa;w.requestPointerLock=w.requestPointerLock||w.mozRequestPointerLock||w.webkitRequestPointerLock;
E.style.cursor="none";Ha();y||ua();setInterval(J,50);x.requestAnimationFrame(ja)}})(window,document);
